### PR TITLE
Allow removing / replacing undefined array elements

### PR DESCRIPTION
**Pull request by andreas-gruenbacher**
The following operations currently fail:
 ```
jsonpatch.apply([,1], {"op":"replace","path":"/0","value":0})
/* expected result: [0,1] */

jsonpatch.apply([,1], {"op":"remove","path":"/0"})
/* expected result: [1] */
```
When converted to JSON, the array would turn into ```[null,1]``` and the above
operations would succeed.

However, it is a common use case to apply patches to JavaScript objects
which are not proper JSON, and it seems reasonable to expect jsonpatch
to treat objects like their JSON equivalents in that case. In particular,
jsonpatch should allow to remove or replace undefined
array elements.  This commit enables that.

### CODE REVIEW

**Comment by bruth** [comment]
@andreas-gruenbacher First, thanks for the contribution. Does this change adhere with the [JSON-Patch spec](https://tools.ietf.org/html/rfc6902)?

**Comment by andreas-gruenbacher** [comment]
JSON doesn't have sparse arrays, so strictly speaking, this behavior is not defined by the JSON-Patch spec. However, if we treat sparse arrays as their JSON equivalents (in the example, ```[null,1]``` instead of ```[,1]```), it seems obvious that the described kinds of operations should succeed.

A related case is a patch that adds array elements beyond the end of the array:
```
jsonpatch.apply([], {"op":"add","path":"/1","value":1})
```
The JSON-Patch spec says that _the specified index MUST NOT be greater than the number of elements in the array,_ so that operation is still an error.

**Comment by andreas-gruenbacher** [comment]
Since this pull request is two weeks old already, can it please be merged? Thanks.

**Comment by andreas-gruenbacher** [comment]
Thank you.

**Pull request merged**
